### ISSUE TITLE
Create React App react-scripts package requires a dependency: "babel-jest": "^24.9.0

### ISSUE THREAD

**Issue by hasante** [creativetimofficial/argon-dashboard-react#28] opened 2020-03-17 15:46 UTC
Found a solution:

All I did was delete the files one after each other in the path below, find yours.
C:\Users\YOURUSERNAME\node_modules\babel-jest (version: 25.1.0)

Then delete, delete one and run again to get what to delete:

Babel-jest
Jest
Webpack
The idea of the solution was in my logs:
Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-jest was detected higher up in the tree:

C:\Users\Henry Asante\node_modules\babel-jest (version: 25.1.0)

**Comment by hasante** [comment] 2020-03-17 16:06
Also:
**1."babel-jest" is not in the dependencies**

**2. The below steps do not work**

To fix the dependency tree, try following the steps below in the exact order:
  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "babel-jest" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

**Comment by einazare** [comment] 2020-03-17 17:28
Hello there, @Henry-Asante ,

Please check our live docs here: https://demos.creative-tim.com/argon-dashboard-react/#/documentation/build-tools
Unfortunately, we do not offer support for Yarn.
I will leave this issue open, with the label of Help Wanted, and if in 30 days nobody will be able to help you, I will close the issue.

The only problem this product has, as of the moment, is the react-scripts package, which you should change to 3.4.0:
```
npm i -E react-scripts@3.4.0
```

Best,
Manu

**Comment by hasante** [comment] 2020-03-17 17:59
**Found a solution:**

All I did was delete the files one after each other in the path below, find yours.
  **C:\Users\YOURUSERNAME\node_modules\babel-jest (version: 25.1.0)** 

**Then delete, delete one and run again to get what to delete:**
1. Babel-jest
2. Jest
3. Webpack


**The idea of the solution was in my logs:**
Don't try to install it manually: your package manager does it automatically.     
However, a different version of babel-jest was detected higher up in the tree:   

C:\Users\Henry Asante\node_modules\babel-jest (version: 25.1.0)

**Comment by hasante** [comment] 2020-03-17 17:59
Leave this open for anyone who needs to know about this

**Comment by truonghdpk** [comment] 2020-03-18 05:44
yes, i got this issue npm install can't install all package we need, i means after install i'm running "npm start" got with react-script not found 
The best way using yarn instead using npm, if you already install with npm
- delete package-lock.json
- delete node_modules
try "yarn" sure you install yarn in your environment before

**Comment by benjhanbs** [comment] 2020-04-08 12:04
@Henry-Asante i didn't understand what you did...
can you explain?

**Comment by hasante** [comment] 2020-04-08 14:25
Okay so then, the problem is that when node installs modules:
```
npm --g install henry
```
This is installed in a universal folder, here in my case **C:\Users\Henry Asante\node_modules\**

So the problem arises when you run a project somewhere else: **C:\Users\Henry Asante\Desktop\project\project**

So when you run 
```
react-scripts start
```

The packages in **C:\Users\Henry Asante\node_modules\** conflict with the ones in **C:\Users\Henry Asante\Desktop\project\project**

So then the project takes the packages in **C:\Users\Henry Asante\node_modules\** instead of the one in **C:\Users\Henry Asante\Desktop\project\project**.

Because of this, it can't compile because the internal paths to the packages are not aligned with the one in the project your working on.

**Comment by hasante** [comment] 2020-04-08 14:26
So to solve it, you have to take away the one higher in the tree: **C:\Users\Henry Asante\node_modules**

**Comment by hasante** [comment] 2020-04-08 14:28
In my case, these packages were conflicting with my project:

- Babel-jest
- Jest
- Webpack

**C:\Users\Henry Asante\node_modules\babel-jest (version: 25.1.0)** etc

So delete them, and the problem is solved

**Comment by hasante** [comment] 2020-04-08 14:28
@benjhanbs

**Comment by benjhanbs** [comment] 2020-04-08 15:34
my case is quite the same, I have a server folder (nodejs) witch has node_modules inside, and inside the server folder, I have a client (react) folder with node_modules as well.
now, I have the same problem because of the server node_modules folder conflicts with the clients node_modules folder.
if I just remove the babel-jest (or any other module) from the server folder, whoever tries to clone this project and will run npm install will have the same problem...
can I enforce the client folder to use only the node_modules in the client folder ?
or you might have a different solution?

thanks for your help!
@Henry-Asante

**Comment by hasante** [comment] 2020-04-09 01:43
Okay I understand you, but I would say the only solution here is to take out the **client folder** and put it at the same level as the **server folder**.

When deploying you will build the client, into most likely a build folder, then you copy that into the public folder of your node.js server and that's how it done.

Write a script to do so if you find it repetitive. ( This is for a project I worked on),
update it to fit yours if you want.
 

```
@echo off
prompt Automating:
cls 

title Automating React build then AWS CI Update

REM first cd into client 
REM then copy the build files into the backend folder
REM then go to the backend folder
color a
cd "D:\Desktop\project\client" && npm run build && color b && xcopy "D:\Desktop\project\client\build" "D:\Desktop\project\public" /e /i /h /Y && cd "D:\Desktop\project\backend" && color d &&  git add . && git commit -m "update" && git push origin backend && cd ..

```

**Comment by hasante** [comment] 2020-04-09 01:44
@benjhanbs

**Comment by RitikaJain8818** [comment] 2020-04-19 10:58
@Henry-Asante 
I am facing the exact same issue.
I tried the suggested steps by deleting babel-jest but no luck.
Can you help?

**Comment by einazare** [comment] 2020-04-19 11:21
Hello there, @RitikaJain8818 ,

You have the exact same issue using `yarn`?
If so, could you try using `npm` instead: https://demos.creative-tim.com/argon-dashboard-react/#/documentation/build-tools ?

Best,
Manu

**Comment by RitikaJain8818** [comment] 2020-04-20 06:23
@EINazare 
I have tried with both yarn and npm, but still facing the same issue.

**Comment by hasante** [comment] 2020-04-20 11:41
@RitikaJain8818 print out your log details here so I can have a full picture of the problem

**Comment by RitikaJain8818** [comment] 2020-04-20 12:12
![Capture](https://user-images.githubusercontent.com/46858658/79750201-2c1c2e00-832e-11ea-94bd-f38f8f2dbbbb.PNG)

@Henry-Asante 
Please check the issue and let me know.

**Comment by hasante** [comment] 2020-04-20 16:37
**C:\Users\YOURNAME\node_modules**

Screenshot this folder for me @RitikaJain8818

**Comment by RitikaJain8818** [comment] 2020-04-20 16:42
Are you sure?
Cause it contains 1027 items.
@Henry-Asante 

Btw I tried deleting babel-jest, jest and webpack.
But no luck

**Comment by hasante** [comment] 2020-04-20 16:44
Okay go to b section and find **babel-jest** @RitikaJain8818

**Comment by RitikaJain8818** [comment] 2020-04-20 16:45
@Henry-Asante 
What, after finding it?

**Comment by hasante** [comment] 2020-04-20 17:00
Delete it @RitikaJain8818 , The whole folder

**Comment by RitikaJain8818** [comment] 2020-04-20 17:02
I have tried running npm start even after deleting it.
But still facing the same issue.
@Henry-Asante

**Comment by hasante** [comment] 2020-04-20 17:10
Is **babel** still in the folder.
Also print out the new errors
@RitikaJain8818

**Comment by RitikaJain8818** [comment] 2020-04-20 17:12
babel or babel-jest?
@Henry-Asante 
And still showing exactly the same errors as in the screenshot I shared.

**Comment by hasante** [comment] 2020-04-21 02:33
@RitikaJain8818 both, and then also search for other ways to get help. Saw a lot of StackOverflow solutions before doing things my own way

**Comment by carl32crc** [comment] 2020-04-28 10:37
@Henry-Asante Same issue for here, I create new project with 'yarn create react-app my-app --template typescript' or 'npx create-react-app my-app --template typescript' and show same message in terminal @RitikaJain8818  after run "yarn start" or "npm start", and i have tried all steps previously discussed.

**Comment by collinzo10** [comment] 2020-05-01 03:47
@Henry-Asante ..Thanks a million for your feedback cuz i have been having the same problem for 2 weeks now. now i am back on track with my project! 👍

**Comment by hasante** [comment] 2020-05-01 23:12
@collinzo10 Your welcome, all the best!

**Comment by KaidenCoder** [comment] 2020-05-24 05:42
The solution that worked for me

> If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
> That would permanently disable this preflight check in case you want to proceed anyway.

**Comment by hasante** [comment] 2020-05-24 14:56
@Kurosakicoder The problem with that is, it fails to build in production

**Comment by hasante** [comment] 2020-05-24 14:57
So what your doing is skipping any checks, but building the product requires these checks, try to build and deploy and let's see. I might be wrong

**Comment by Kurosakicoder** [comment] 2020-05-24 17:01
> @Kurosakicoder The problem with that is, it fails to build in production

Nope my website was on netlify and after still adding .env, it does not effect in production

**Comment by KaidenCoder** [comment] 2020-05-24 17:02
@Henry-Asante 
my website was on netlify and after still adding .env, it does not effect in production

**Comment by hasante** [comment] 2020-05-24 17:04
Okay that's great to know, someone else might need it. Thanks for contributing.

**Comment by PhiPhiPhi** [comment] 2020-06-19 15:57
Thanks a lot @Henry-Asante! your solution works for me :)

**Comment by hasante** [comment] 2020-06-19 18:41
@PhiPhiPhi Most welcome

**Comment by ManjeetKumarSingh** [comment] 2020-06-26 20:24
@RitikaJain8818 
Please go to your path 
 `C:\Users\YOURNAME\node_modules`
and then remove those packages which shows an error, in your case 
`rm -rf bable-jest `

Likewise, if it shows more such error please remove all one by one using `rm-rm  <the package which having error>`

**Comment by leoamsbb** [comment] 2020-07-15 04:26
Thanks a lot @Henry-Asante 

I faced this issue on Mac and your solution of deleting babel-jest and jest worked for me!

**Comment by BasharSaleh92** [comment] 2020-07-20 13:52
I faced this issue when I create a nodejs application and inside it, I created a react app in a subdirectory.
the solution was by deleting Jest and babel-jest and anything related to them (@types/jest, ts-jest, ....) from package.json that related to nodejs project (parent one) and it works fine 👍 .

**Comment by hasante** [comment] 2020-07-20 14:57
@BasharSaleh92 @mrunal-badhe Your welcome

**Comment by Ishaan28malik** [comment] 2020-08-21 13:57
The issue is occurring either because you have already defined a set of `node_modules` in an outer/some-other `Directory` and in that node_modules the version of `@babel-jest` is ahead asper the mentioned **Create React App** docs.
The current version asked by **Create React App**  is `24.9.0`.
Your version in that directory you might be using `25.3.0`

**Comment by emilioramirezeguia** [comment] 2020-09-21 19:53
Thank you @Henry-Asante, this was driving me crazy 🤯

**Comment by kayacancode** [comment] 2020-09-28 14:23
Thank you @Ishaan28malik

**Comment by AkiraBrand** [comment] 2020-12-19 23:28
@Henry-Asante Dude, you literally saved my life by posting this fix. I also went into my root c:users/ruthbrand folder and deleted node_modules and package-lock.json and now my dev server works just fine. Thank you!!

**Closed as completed** 2021-01-22 15:33 UTC
Labels: help wanted

**Comment by djguruwap** [comment] 2021-05-31 12:10
In my case i am using linux and somehow i have installed npm as gobal. So, i just remove the node_modules and its working fine now,

**Comment by angle361** [comment] 2022-11-27 08:43
> ![Capture](https://user-images.githubusercontent.com/46858658/79750201-2c1c2e00-832e-11ea-94bd-f38f8f2dbbbb.PNG)
> 
> @Henry-Asante Please check the issue and let me know.

issue solved?

**Comment by sajadevo** [comment] 2022-11-28 07:11
@angle361,

Please check the latest version of the product, we don't have any issue like that now.

Regards,
Sajad

**Comment by boluwatifeajayi** [comment] 2023-06-21 18:44
check your version of react-scripts 
uninstall it and install it back to get the latest version

**Comment by kwesisam** [comment] 2024-01-21 01:26
For me, this one works .

npm install --save --save-exact react-scripts@5.0.1
or
yarn add --exact react-scripts@5.0.1

https://github.com/facebook/create-react-app/blob/main/CHANGELOG.md#301-2019-05-08
