### ISSUE TITLE
    "react-scripts": "3.3.1" path error

### ISSUE THREAD

**Issue by burakkilic** [creativetimofficial/argon-dashboard-react#23] opened 2020-02-21 15:44 UTC
Hi,

I've just installed the template but received path unresolved.

Fixed after changing the package.json 

    "react-scripts": "3.3.1",
to

    "react-scripts": "^3.4.0"

https://stackoverflow.com/questions/60234640/typeerror-err-invalid-arg-type-the-path-argument-must-be-of-type-string-re/60242323#60242323

**Comment by gilbert-p** [comment] 2020-02-25 14:35
Hey thanks man! I was stuck and wondering what was going on after installing it.

**Comment by einazare** [comment] 2020-02-25 15:33
Hello guys,

I'll try to make an update with this fix as soon as possible, right now, for this week it is scheduled the Pro version of the Black Dashboard React.
Leave this issue opened.

Best,
Manu

**Comment by talglobus** [comment] 2020-03-16 22:44
Any progress on this? I'm still seeing the same error

**Comment by talglobus** [comment] 2020-03-16 23:06
The problem is due to the version of react scripts used. Fixed in pull request above

**Comment by Master244** [comment] 2020-11-03 16:43
The download from the site still has the zip with the wrong react scripts version. Led me here at least. Just to let you know.

**Closed as completed** 2021-01-26 14:31 UTC
Labels: bug
